Made `rejectUnauthorized` depend on NODE_TLS_REJECT_UNAUTHORIZED
npm/minipass-fetch pull request #12
Opened 2021-04-21 10:35 UTC by svennergr

Setting `NODE_TLS_REJECT_UNAUTHORIZED` in node will disable the ssl certificate verification. Minipass-fetch is currently unaware of this option.

## References
Fixes #11

2021-05-02 15:42 UTC, lastthyme approved these changes

2021-05-02 15:55 UTC, lastthyme approved these changes

2021-06-29 17:44 UTC, isaacs requested changes
Fine to add awareness of this environment variable, but I think this patch does the exact opposite of what we want, _only_ rejecting unauthorized when it's set to `'0'`.  We want to reject unauthorized _unless_ it's set to `'0'`.

Also: needs a test.

2021-06-29 17:44 UTC, isaacs commented on lib/request.js
> +      rejectUnauthorized = process.env.NODE_TLS_REJECT_UNAUTHORIZED === '0',
```suggestion
      rejectUnauthorized = process.env.NODE_TLS_REJECT_UNAUTHORIZED !== '0',
```

2021-06-30 06:11 UTC, svennergr commented
Thanks for the review @isaacs. 
I updated the PR accordingly.

2021-08-31 16:10 UTC, isaacs commented
Landed on 706d0ad85d47fcf255c2af4bab68b064d470364c

Thanks!

2021-08-31 16:10 UTC, closed without merging